USE master
GO
IF DB_ID('QuanLyNhaHang') IS NOT NULL
	DROP DATABASE QuanLyNhaHang
GO
CREATE DATABASE QuanLyNhaHang
GO
USE QuanLyNhaHang;
GO
-- Table: KHACH_HANG
CREATE TABLE KHACH_HANG (
    MA_KH CHAR(10),
    HOTEN NVARCHAR(100) not null,
    SDT CHAR(10) CONSTRAINT UQ_SDT UNIQUE,
    EMAIL VARCHAR(100),
    CCCD CHAR(12),
    GIOITINH NVARCHAR(1) CONSTRAINT CK_GIOITINH CHECK (GIOITINH IN ('M', 'F')),
    DIACHI NVARCHAR(50),
	CONSTRAINT PK_KHACHHANG PRIMARY KEY (MA_KH)
);
--PK: MA_THE
-- Table: THE_THANH_VIEN
CREATE TABLE THE_THANH_VIEN (
    MA_THE CHAR(10),
	MA_KH CHAR(10),
    NGAYLAP DATE,
	MA_NV CHAR(10),
    LOAITHE NVARCHAR(50) NOT NULL,
    DIEM_TICHLUY INT,
	HOAT_DONG_THE BIT,
    NGAY_CAPNHAT DATE,
	CONSTRAINT PK_THETHANHVIEN PRIMARY KEY (MA_THE)
);
--PK: MA_NV
-- Table: UU_DAI
CREATE TABLE UU_DAI (
    MA_UD CHAR(10),
	MA_THE CHAR(10),
    TEN_UD VARCHAR(100),
    GIAMGIA FLOAT,
    DIEUKIEN NVARCHAR(255),
    NGAY_BD DATE,
    NGAY_KT DATE,
	CONSTRAINT CK_UD_BDKT CHECK (NGAY_BD < NGAY_KT),
	CONSTRAINT PK_UUDAI PRIMARY KEY (MA_UD, MA_THE)
);
--PK: MA_THE
-- Table: PHIEU_DAT
CREATE TABLE PHIEU_DAT (
    MA_PHIEU CHAR(10),
    MA_KH CHAR(10),
    MA_NV CHAR(10),
    NGAY_DAT DATE,
	TRANG_THAI NVARCHAR(15),
	CONSTRAINT CK_CTPD_TT CHECK (TRANG_THAI IN ( 'Đang xử lý','Đã giao')),
	CONSTRAINT PK_PHIEUDAT PRIMARY KEY (MA_PHIEU)
);
--PK, MA_KH, MA_NV
-- Table: CHI_TIET_PHIEU
CREATE TABLE CHI_TIET_PHIEU (
    MA_PHIEU CHAR(10),
    MA_MON CHAR(10),
    SO_LUONG INT,

	CONSTRAINT PK_CHITIETPHIEUDAT PRIMARY KEY (MA_PHIEU, MA_MON)
);
--PK: MA_PHIEU, MA_MON
-- Table: DON_HANG_ONLINE
CREATE TABLE DON_HANG_ONLINE (
    MA_DONHANG CHAR(10),
    MA_KH CHAR(10),
    NGAY_DAT DATE,
    TRANGTHAI NVARCHAR(50),
    MA_TAIXE CHAR(10),
	CONSTRAINT PK_DONHANGONLINE PRIMARY KEY (MA_DONHANG)
);
--PK: MA_KH, MA_TAIXE
-- Table: CHI_TIET_DON_HANG_ONLINE
CREATE TABLE CHI_TIET_DON_HANG_ONLINE (
	MA_DONHANG CHAR(10),
    MA_MON CHAR(10),
    SO_LUONG INT,
	CONSTRAINT PK_CTDONHANG PRIMARY KEY (MA_DONHANG, MA_MON)
);
--PK: MA_MON
-- Table: HOA_DON
CREATE TABLE HOA_DON (
    MA_HOADON CHAR(10),
	MA_DONHANG CHAR(10),
	MA_PHIEU CHAR(10),
    TONG_TIEN FLOAT,
    GIAM_GIA FLOAT,
    NGAY_LAP DATE,
    LOAI_HOADON NVARCHAR (20),
	CONSTRAINT CK_LOAIHOADON CHECK (LOAI_HOADON IN ('Trực tiếp' , 'ONLINE')),
	CONSTRAINT PK_HOADON PRIMARY KEY (MA_HOADON)
);
--PK: MA_DONHANG, MA_PHIEU
-- Table: CHI_NHANH
CREATE TABLE CHI_NHANH (
    MA_CHINHANH CHAR(10),
    TEN_CHINHANH NVARCHAR(100),
    TG_MO TIME,
    TG_DONG TIME,
    SDT CHAR(10),
    BD_XEMAY NVARCHAR(10) CONSTRAINT CK_CN_XM CHECK (BD_XEMAY IN('Còn', 'Hết')),
    BD_XEHOI NVARCHAR(10) CONSTRAINT CK_CN_XH CHECK (BD_XEHOI IN('Còn' ,'Hết')),
    DIACHI NVARCHAR(255),
	CONSTRAINT PK_CHINHANH PRIMARY KEY (MA_CHINHANH)
);

-- Table: BO_PHAN
CREATE TABLE BO_PHAN (
    MA_BOPHAN CHAR(10),
    TENBP VARCHAR(100),
	CONSTRAINT PK_BOPHAN PRIMARY KEY (MA_BOPHAN)
);

-- Table: NHAN_VIEN
CREATE TABLE NHAN_VIEN (
    MA_NV CHAR(10),
	MA_QUANLI CHAR(10),
	MA_CHINHANH CHAR(10),
    HOTEN NVARCHAR(100),
    MA_BOPHAN CHAR(10),
    NGSINH DATE,
    GIOITINH CHAR(1),
    SDT CHAR(10),
    LUONG FLOAT,
    DIEM_PV FLOAT,
    NGAY_BD DATE,
    NGAY_KT DATE,
	CONSTRAINT PK_NHANVIEN PRIMARY KEY (MA_NV)
);
--PK: MA_BOPHAN, MA_NV, MA_CHINHANH
-- Table: DOANH_THU
CREATE TABLE DOANH_THU (
    MA_DOANHTHU CHAR(10),
    MA_CHINHANH CHAR(10),
    DOANH_THU FLOAT,
    NGAY DATE,
	CONSTRAINT PK_DOANHTHU  PRIMARY KEY (MA_DOANHTHU)
);
--PK: MA_CHINHANH
-- Table: THUC_DON
CREATE TABLE THUC_DON (
    MA_THUCDON CHAR(10),
	MA_MON CHAR(10),
    TEN_THUCDON NVARCHAR(100),
    MA_CHINHANH CHAR(10),
    CONSTRAINT PK_THUCDON  PRIMARY KEY (MA_THUCDON, MA_MON)	
);
--PK: MA_MON, MA_CHINHANH
-- Table: MON_AN
CREATE TABLE MON_AN (
    MA_MON CHAR(10),
    TEN_MON NVARCHAR(100),
    GIA FLOAT,
    TRANGTHAI_PHUCVU BIT,
	CONSTRAINT PK_MONAN PRIMARY KEY (MA_MON)
);

-- Table: TAI_XE
CREATE TABLE TAI_XE (
    MA_TAIXE CHAR(10),
    HOTEN VARCHAR(100),
    SDT CHAR(10),
    BIEN_SO VARCHAR(20),
	CONSTRAINT PK_TAIXE PRIMARY KEY (MA_TAIXE)
);

-- Table: DANH_GIA
CREATE TABLE DANH_GIA (
    MA_DANHGIA CHAR(10),
    MA_KH CHAR(10),
    MA_CHINHANH CHAR(10),
    MA_TAIXE CHAR(10),
	MA_MON CHAR(10),
	DIEMPHUCVU FLOAT,
	DIEMCHINHANH FLOAT,
	DIEMCHATLUONGMON FLOAT,
	DIEMGIACA FLOAT,
	DIEMTAIXE FLOAT,
    NOIDUNG NVARCHAR(255),
    NGAY_DANHGIA DATE,
	CONSTRAINT PK_DANHGIA PRIMARY KEY (MA_DANHGIA, MA_KH)
);
--PK: MA_CHINHANH, MA_TAIXE, MA_KH, MA_MON
-- 
-- 
-- 
-- 
-- 
-- 
-- 
-- 
-- THUC DON THI THAM CHIEU TOI CHI NHANH, MON AN
-- 
-- DOANH THU THI THAM CHIEU TOI CHI NHANH
-- DANH GIA THI THAM CHIEU TOI KHACH HANG, TAI XE, CHI NHANH, MON AN
-- 
-- DON HANG ONLINE THI THAM CHIEU TOI KHACH HANG, TAI XE, CHI TIET DON HANG
-- CHI TIET DON HANG THI THAM CHIEU TOI MON AN
-- HOA DON THI THAM CHIEU TOI DON HANG ONLINE, PHIEU DAT
ALTER TABLE THE_THANH_VIEN 
ADD CONSTRAINT FK_THETHANHVIEN1 FOREIGN KEY (MA_KH)
REFERENCES KHACH_HANG(MA_KH)

ALTER TABLE THE_THANH_VIEN
ADD CONSTRAINT FK_THETHANHVIEN2 FOREIGN KEY (MA_NV)
REFERENCES NHAN_VIEN (MA_NV)

ALTER TABLE UU_DAI
ADD CONSTRAINT FK_UUDAI FOREIGN KEY (MA_THE)
REFERENCES THE_THANH_VIEN (MA_THE)

ALTER TABLE PHIEU_DAT
ADD CONSTRAINT FK_PHIEUDAT1 FOREIGN KEY (MA_KH)
REFERENCES KHACH_HANG (MA_KH)

ALTER TABLE PHIEU_DAT
ADD CONSTRAINT FK_PHIEUDAT2 FOREIGN KEY (MA_NV)
REFERENCES NHAN_VIEN (MA_NV)

ALTER TABLE CHI_TIET_PHIEU
ADD CONSTRAINT FK_CTPHIEU1 FOREIGN KEY (MA_PHIEU)
REFERENCES PHIEU_DAT (MA_PHIEU)

ALTER TABLE CHI_TIET_PHIEU
ADD CONSTRAINT FK_CTPHIEU2 FOREIGN KEY (MA_MON)
REFERENCES MON_AN (MA_MON)

ALTER TABLE DON_HANG_ONLINE
ADD CONSTRAINT FK_DONHANG1 FOREIGN KEY (MA_KH)
REFERENCES KHACH_HANG (MA_KH)

ALTER TABLE DON_HANG_ONLINE
ADD CONSTRAINT FK_DONHANG2 FOREIGN KEY (MA_TAIXE)
REFERENCES TAI_XE (MA_TAIXE)

ALTER TABLE CHI_TIET_DON_HANG_ONLINE
ADD CONSTRAINT FK_CTDONHANG2 FOREIGN KEY (MA_DONHANG)
REFERENCES DON_HANG_ONLINE (MA_DONHANG)

ALTER TABLE CHI_TIET_DON_HANG_ONLINE
ADD CONSTRAINT FK_CTDONHANG1 FOREIGN KEY (MA_MON)
REFERENCES MON_AN (MA_MON)

ALTER TABLE HOA_DON
ADD CONSTRAINT FK_HOADON1 FOREIGN KEY (MA_DONHANG)
REFERENCES DON_HANG_ONLINE (MA_DONHANG)

ALTER TABLE HOA_DON
ADD CONSTRAINT FK_HOADON2 FOREIGN KEY (MA_PHIEU)
REFERENCES PHIEU_DAT (MA_PHIEU)

ALTER TABLE NHAN_VIEN
ADD CONSTRAINT FK_NHANVIEN1 FOREIGN KEY (MA_QUANLI)
REFERENCES NHAN_VIEN (MA_NV)

ALTER TABLE NHAN_VIEN
ADD CONSTRAINT FK_NHANVIEN2 FOREIGN KEY (MA_CHINHANH)
REFERENCES CHI_NHANH (MA_CHINHANH)

ALTER TABLE NHAN_VIEN
ADD CONSTRAINT FK_NHANVIEN3 FOREIGN KEY (MA_BOPHAN)
REFERENCES BO_PHAN (MA_BOPHAN)

ALTER TABLE DOANH_THU
ADD CONSTRAINT FK_DOANHTHU1 FOREIGN KEY (MA_CHINHANH)
REFERENCES CHI_NHANH (MA_CHINHANH)

ALTER TABLE THUC_DON
ADD CONSTRAINT FK_THUCDON1 FOREIGN KEY (MA_CHINHANH)
REFERENCES CHI_NHANH (MA_CHINHANH)

ALTER TABLE THUC_DON
ADD CONSTRAINT FK_THUCDON2 FOREIGN KEY (MA_MON)
REFERENCES MON_AN (MA_MON)

ALTER TABLE DANH_GIA
ADD CONSTRAINT FK_DANHGIA1 FOREIGN KEY (MA_CHINHANH)
REFERENCES CHI_NHANH (MA_CHINHANH)

ALTER TABLE DANH_GIA
ADD CONSTRAINT FK_DANHGIA2 FOREIGN KEY (MA_KH)
REFERENCES KHACH_HANG (MA_KH)

ALTER TABLE DANH_GIA
ADD CONSTRAINT FK_DANHGIA3 FOREIGN KEY (MA_TAIXE)
REFERENCES TAI_XE (MA_TAIXE)

ALTER TABLE DANH_GIA
ADD CONSTRAINT FK_DANHGIA4 FOREIGN KEY (MA_MON)
REFERENCES MON_AN (MA_MON)
