--Thêm chi tiết phiếu đặt
CREATE PROCEDURE SP_ThemChiTietPhieu
    @MA_PHIEU CHAR(10),
    @MA_MON CHAR(10),
    @SO_LUONG INT,
    @TRANG_THAI NVARCHAR(15)
AS
BEGIN
    INSERT INTO CHI_TIET_PHIEU (MA_PHIEU, MA_MON, SO_LUONG, TRANG_THAI)
    VALUES (@MA_PHIEU, @MA_MON, @SO_LUONG, @TRANG_THAI);
END;
GO
--Cập nhật số lượng món trong phiếu
CREATE PROCEDURE SP_CapNhatChiTietPhieu
    @MA_PHIEU CHAR(10),
    @MA_MON CHAR(10),
    @SO_LUONG INT
AS
BEGIN
    UPDATE CHI_TIET_PHIEU
    SET SO_LUONG = @SO_LUONG
    WHERE MA_PHIEU = @MA_PHIEU AND MA_MON = @MA_MON;
END;
GO
--Xóa chi tiết phiếu
CREATE PROCEDURE SP_XoaChiTietPhieu
    @MA_PHIEU CHAR(10),
    @MA_MON CHAR(10)
AS
BEGIN
    DELETE FROM CHI_TIET_PHIEU
    WHERE MA_PHIEU = @MA_PHIEU AND MA_MON = @MA_MON;
END;
GO
--Tìm kiếm chi tiết phiếu đặt dựa trên MA_PHIEU
CREATE PROCEDURE SP_TimKiemChiTietPhieu
    @MA_PHIEU CHAR(10)
AS
BEGIN
    SELECT MA_MON, SO_LUONG, TRANG_THAI
    FROM CHI_TIET_PHIEU
    WHERE MA_PHIEU = @MA_PHIEU;
END;

GO

GO
--Lấy chi tiết các món ăn theo trạng thái 'ĐANG XỬ LÝ' hoặc 'ĐÃ GIAO'
CREATE PROCEDURE SP_LayChiTietTheoTrangThai
    @TRANG_THAI NVARCHAR(15)
AS
BEGIN
    SELECT MA_PHIEU, TRANG_THAI
    FROM	PHIEU_DAT
    WHERE TRANG_THAI = @TRANG_THAI;
END;
GO
--Cập nhật trạng thái món ăn
CREATE PROCEDURE SP_CapNhatTrangThaiMon
    @MA_PHIEU CHAR(10),
    @TRANG_THAI NVARCHAR(15)
AS
BEGIN
    UPDATE MA_PHIEU
    SET TRANG_THAI = @TRANG_THAI
    WHERE MA_PHIEU = @MA_PHIEU
END;

]
