-- Thêm chi tiết đơn hàng online
CREATE PROCEDURE SP_ThemChiTietDonHangOnline
    @MA_DONHANG CHAR(10),
    @MA_MON CHAR(10),
    @SO_LUONG INT
AS
BEGIN
    INSERT INTO CHI_TIET_DON_HANG_ONLINE (MA_DONHANG, MA_MON, SO_LUONG)
    VALUES (@MA_DONHANG, @MA_MON, @SO_LUONG);
END;
GO

-- Xóa chi tiết đơn hàng online
CREATE PROCEDURE SP_XoaChiTietDonHangOnline
    @MA_DONHANG CHAR(10),
    @MA_MON CHAR(10)
AS
BEGIN
    DELETE FROM CHI_TIET_DON_HANG_ONLINE
    WHERE MA_DONHANG = @MA_DONHANG AND MA_MON = @MA_MON;
END;
GO

-- Tìm kiếm chi tiết đơn hàng dựa trên MA_DONHANG
CREATE PROCEDURE SP_TimKiemChiTietDonHang
    @MA_DONHANG CHAR(10)
AS
BEGIN
    SELECT *
    FROM CHI_TIET_DON_HANG_ONLINE
    WHERE MA_DONHANG = @MA_DONHANG;
END;
GO

-- Cập nhật số lượng cho từ chi tiết đơn hàng
CREATE PROCEDURE SP_CapNhatSoLuongChiTietDonHang
    @MA_DONHANG CHAR(10),
    @MA_MON CHAR(10),
    @SO_LUONG INT
AS
BEGIN
    UPDATE CHI_TIET_DON_HANG_ONLINE
    SET SO_LUONG = @SO_LUONG
    WHERE MA_DONHANG = @MA_DONHANG AND MA_MON = @MA_MON;
END;
GO

-- Truy vấn danh sách các món được mua nhiều nhất (JOIN với bảng CHI_TIET_PHIEU_DAT)
CREATE PROCEDURE SP_DanhSachMonMuaNhieuNhat
AS
BEGIN
    SELECT 
        MON_AN.MA_MON,
        MON_AN.TEN_MON,
        SUM(CTDH.SO_LUONG) + ISNULL(SUM(CTPD.SO_LUONG), 0) AS TONG_SO_LUONG
    FROM MON_AN
    LEFT JOIN CHI_TIET_DON_HANG_ONLINE CTDH ON MON_AN.MA_MON = CTDH.MA_MON
    LEFT JOIN CHI_TIET_PHIEU CTPD ON MON_AN.MA_MON = CTPD.MA_MON
    GROUP BY MON_AN.MA_MON, MON_AN.TEN_MON
    ORDER BY TONG_SO_LUONG DESC;
END;
GO
