-- Thêm đơn hàng online khi có khách hàng đặt
CREATE PROCEDURE SP_ThemDonHangOnline
    @MA_DONHANG CHAR(10),
    @MA_KH CHAR(10),
    @NGAY_DAT DATE,
    @TRANGTHAI NVARCHAR(50),
    @MA_TAIXE CHAR(10)
AS
BEGIN
    INSERT INTO DON_HANG_ONLINE (MA_DONHANG, MA_KH, NGAY_DAT, TRANGTHAI, MA_TAIXE)
    VALUES (@MA_DONHANG, @MA_KH, @NGAY_DAT, @TRANGTHAI, @MA_TAIXE);
END;
GO

-- Xóa đơn hàng online khi khách hàng yêu cầu hủy
CREATE PROCEDURE SP_XoaDonHangOnline
    @MA_DONHANG CHAR(10)
AS
BEGIN
    DELETE FROM DON_HANG_ONLINE
    WHERE MA_DONHANG = @MA_DONHANG;
END;
GO

-- Cập nhật: TRANGTHAI_DONHANG, MA_BAN
CREATE PROCEDURE SP_CapNhatDonHangOnline
    @MA_DONHANG CHAR(10),
    @TRANGTHAI NVARCHAR(50),
    @MA_BAN CHAR(10)
AS
BEGIN
    UPDATE DON_HANG_ONLINE
    SET TRANGTHAI = @TRANGTHAI, MA_TAIXE = @MA_BAN
    WHERE MA_DONHANG = @MA_DONHANG;
END;
GO

-- Tìm kiếm đơn hàng online dựa trên: NGAY_DAT, MAKH
CREATE PROCEDURE SP_TimDonHangOnlineTheoNgayVaKH
    @NGAY_DAT DATE,
    @MA_KH CHAR(10)
AS
BEGIN
    SELECT MA_DONHANG, MA_KH, NGAY_DAT, TRANGTHAI, MA_TAIXE
    FROM DON_HANG_ONLINE
    WHERE NGAY_DAT = @NGAY_DAT AND MA_KH = @MA_KH;
END;
GO

-- Tìm kiếm đơn hàng online thông qua NGAY_DAT, MA_BAN
CREATE PROCEDURE SP_TimDonHangOnlineTheoNgayVaBan
    @NGAY_DAT DATE,
    @MA_BAN CHAR(10)
AS
BEGIN
    SELECT MA_DONHANG, MA_KH, NGAY_DAT, TRANGTHAI, MA_TAIXE
    FROM DON_HANG_ONLINE
    WHERE NGAY_DAT = @NGAY_DAT AND MA_TAIXE = @MA_BAN;
END;
GO

-- Cập nhật GIO_DEN, NGAY_DAT khi khách hàng có nhu cầu thay đổi
CREATE PROCEDURE SP_CapNhatNgayVaGioDen
    @MA_DONHANG CHAR(10),
    @NGAY_DAT DATE,
    @GIO_DEN TIME
AS
BEGIN
    UPDATE DON_HANG_ONLINE
    SET NGAY_DAT = @NGAY_DAT, GIO_DEN = @GIO_DEN
    WHERE MA_DONHANG = @MA_DONHANG;
END;
GO

--Liệt kê tất cả đơn hàng trong một khoảng ngày
CREATE PROCEDURE SP_LietKeDonHangTheoKhoangNgay
    @NGAY_BATDAU DATE,
    @NGAY_KETTHUC DATE
AS
BEGIN
    SELECT *
    FROM DON_HANG_ONLINE
    WHERE NGAY_DAT BETWEEN @NGAY_BATDAU AND @NGAY_KETTHUC;
END;
GO

--Thống kê số lượng đơn hàng theo khách hàng
CREATE PROCEDURE SP_ThongKeSoLuongDonHangTheoKH
AS
BEGIN
    SELECT MA_KH, COUNT(*) AS SO_LUONG_DON
    FROM DON_HANG_ONLINE
    GROUP BY MA_KH;
END;
GO

--Lấy danh sách các tài xế giao đơn trong ngày
CREATE PROCEDURE SP_LayDanhSachTaiXeTheoNgay
    @NGAY DATE
AS
BEGIN
    SELECT DISTINCT MA_TAIXE
    FROM DON_HANG_ONLINE
    WHERE NGAY_DAT = @NGAY;
END;
GO

--Liệt kê đơn hàng chưa giao
CREATE PROCEDURE SP_LietKeDonHangChuaGiao
AS
BEGIN
    SELECT *
    FROM DON_HANG_ONLINE
    WHERE TRANGTHAI = 'CHUA GIAO';
END;
GO
