--Thêm khách hàng mới
CREATE PROCEDURE SP_ThemKhachHang
  @MA_KH CHAR(10),
  @HO_TEN NVARCHAR(100),
  @SDT CHAR(10),
  @EMAIL VARCHAR(100),
  @CCCD CHAR(12),
  @GIOITINH NVARCHAR(3),
  @DIACHI NVARCHAR(50)
AS
BEGIN
  INSERT INTO KHACH_HANG (MA_KH, HOTEN, SDT, EMAIL, CCCD, GIOITINH, DIACHI)
  VALUES (@MA_KH, @HO_TEN, @SDT, @EMAIL, @CCCD, @GIOITINH, @DIACHI);
END;

--Tìm kiếm khách hàng 
CREATE PROCEDURE SP_TimKhachHangTheoSDT
  @SDT CHAR(10)
AS
BEGIN
  SELECT * FROM KHACH_HANG WHERE SDT = @SDT;
END;

--Cập nhật thông tin khách hàng
CREATE PROCEDURE SP_CapNhatKhachHang
  @MA_KH CHAR(10),
  @EMAIL VARCHAR(100),
  @DIACHI NVARCHAR(50),
  @SDT CHAR(10)
AS
BEGIN
  UPDATE KHACH_HANG
  SET EMAIL = @EMAIL, DIACHI = @DIACHI, SDT = @SDT
  WHERE MA_KH = @MA_KH;
END;

