--Xem Thông tin món ăn
CREATE PROCEDURE SP_XemDanhSachMonAn
	@MA_MON CHAR(10)
AS
BEGIN
        SELECT *
        FROM MON_AN
		WHERE MA_MON = @MA_MON;
END;
--Cập nhật món ăn
CREATE PROCEDURE SP_CapNhatMonAn
	@MA_MON CHAR(10),
	@TINHTRANG NVARCHAR(50),
	@GIA FLOAT
AS
BEGIN
        UPDATE MON_AN
		SET TRANGTHAI_PHUCVU = @TINHTRANG , GIA = @GIA
		WHERE MA_MON = @MA_MON
END
--Thêm món ăn
CREATE PROCEDURE SP_ThemNhanVien
	@MA_MON CHAR(10),
    @TEN_MON NVARCHAR(100),
    @GIA FLOAT,
    @TRANGTHAI_PHUCVU NVARCHAR(50)
AS
BEGIN
  INSERT INTO MON_AN(MA_MON, TEN_MON, GIA, TRANGTHAI_PHUCVU)
  VALUES (@MA_MON,@TEN_MON,@GIA,@TRANGTHAI_PHUCVU)
END;
--Tìm kiếm món ăn
CREATE PROCEDURE SP_TimMonAnTheoTen
  @TEN_MON NVARCHAR(100)
AS
BEGIN
  SELECT * FROM MON_AN WHERE TEN_MON LIKE '%' + @TEN_MON + '%';
END;
